#!/bin/bash

set -e

git clone --branch gh-pages --depth 1 https://github.com/sidneynemzer/casual-minesweeper deploy
npm run build
cp build/* deploy
cd deploy
git add .
git commit -m "Deploy"
git push
cd ..
rm -rf deploy
