#!/bin/bash

set -e

git clone --branch gh-pages --depth 1 git@github.com:SidneyNemzer/casual-minesweeper.git deploy
npm run build
cp build/* deploy
cd deploy
git add .
git commit -m "Deploy"
git push
cd ..
rm -rf deploy
